create table "user"
(
    id       bigint generated by default as identity
        constraint user_pkey
            primary key,
    email    varchar(255),
    password varchar(255),
    username varchar(255)
        constraint uk_username
            unique
);

alter table "user"
    owner to postgres;

