create table product_major_category
(
    id   bigint generated by default as identity
        constraint product_major_category_pkey
            primary key,
    name varchar(255)
);

alter table product_major_category
    owner to postgres;

