create table product_review_vote
(
    id        bigint generated by default as identity
        constraint product_review_vote_pkey
            primary key,
    positive  boolean not null,
    review_id bigint
        constraint fk__review_id
            references product_review,
    user_id   bigint
        constraint fk__user_id
            references "user"
);

alter table product_review_vote
    owner to postgres;

